#ifndef MY_HROMAT_900_INI_SEKTS_HEADER_INCLUDED____
#define MY_HROMAT_900_INI_SEKTS_HEADER_INCLUDED____



typedef const char* const ConstCharPtrConst;




/*
*				имена секций ini файла приложения
*/
ConstCharPtrConst
	MAIN_HROMAT_INI_SEKT = "MAIN",
    	BACKUP_INTERVAL_MINUTES = "BACKUP_INTERVAL_MINUTES",
    	HTGS_DIR_SEKT = "HTGS_DIRECTRORY",
	//MAINFORM_SEKT = "MAINFORM",
        RIGHT_PANELS_SELECTION = "RIGHT_PANELS_SELECTION",
        RIGHT_PANEL_WIDTH = "RIGHT_PANEL_WIDTH",
        STATUS_PANEL_WIDTH = "STATUS_PANEL_WIDTH", 
        RIGHT_PANEL_GRID_VISIBLE_ROWS = "RIGHT_PANEL_GRID_VISIBLE_ROWS",
        DETECTOR_SERIES_COLOR 			= "DETECTOR_SERIES_COLOR",
        DETECTOR_SERIES_LINE_WIDTH 		= "DETECTOR_SERIES_LINE_WIDTH",
        DETECTOR_CHART_COLOR 			= "DETECTOR_CHART_COLOR",
        DETECTOR_CHART_BACKCOLOR 		= "DETECTOR_CHART_BACKCOLOR",
        DETECTOR_PIK_TBL_VIS_COLS 		= "PIK_TBL_VIS_COLS",

        EVTS_JRNL_FORM_VISIBLE = "EVTS_JRNL_FORM_VISIBLE",

    HROMAT_9001_EXPORT_ANALYZE_TO_EXCEL_DLG = "HROMAT_9001_EXPORT_ANALYZE_TO_EXCEL_DLG",
        EXPORT_ANALYZE_TO_EXCEL_CONC = "EXPORT_ANALYZE_TO_EXCEL_CONC",
        EXPORT_ANALYZE_TO_EXCEL_PHYSCHEM = "EXPORT_ANALYZE_TO_EXCEL_PHYSCHEM",
        EXPORT_ANALYZE_TO_EXCEL_DCONC = "EXPORT_ANALYZE_TO_EXCEL_DCONC",
        EXPORT_ANALYZE_TO_EXCEL_DPHYSCHEM = "EXPORT_ANALYZE_TO_EXCEL_DPHYSCHEM",

        EXPORT_ANALYZE_TO_EXCEL_TEMPLATE_PATH = "TEMPLATE_PATH",

	TRANSFERS_SEKT = "TRANSFERS",
	    TRANSFERS_THREAD_PRIORITY_ID = "THREAD_PRIORITY",
    	MODBUS_DEVICE_ADDRESS = "MODBUS_DEVICE_ADDRESS",
    	TCP_ACTIVE_ID = "TCPACTIVE",
        WRITE_DELAY_ID = "WRITEDELAY",
        TIME_OUT_ID = "TIMEOUT",
        MAXIMUM_RXD_FRAME_SIZE = "MAXIMUM_RXD_FRAME_SIZE",
        RXD_FRAME_SILENT_TIME = "RXD_FRAME_SILENT_TIME",

	COMPORT_SEKT = "COMPORT",
    	COMPORT_IDX_ID = "Port",
        COMPORT_BOUDRATE_ID = "BaudRate",
    TCP_SEKT = "TCP",
    	IP_ADDRESS_ID = "Ip",
    	IP_HOST_ID = "Host",
    	TCP_PORT_NUM_ID = "Port",
        USE_PROXI_ID = "использовать_прокси_сервер",
        PROXI_SERVER_ID = "прокси_сервер",

    // журнал событий
    EVENTS_JOURNAL_NODE = "EVENTS_JOURNAL",
        EVTS_JRNL_FORM_COLWIDTH = "EVTS_JRNL_FORM_COLWIDTH",
        EVTS_JRNL_MAX_FILE_SIZE = "EVTS_JRNL_MAX_FILE_SIZE",
        EVTS_JRNL_LAST_FILE = "EVTS_JRNL_LAST_FILE"

;//				имена секций ini файла приложения
//------------------------------------------------------------------------------

#define SOFTWARE_REG_KEY                        "\\Software"
#define HROMAT_9001_SEKT                        "Хромат-900"
#define HROMAT_9001_EVENTS_JOURNAL_SEKT            "EVENTS_JOURNAL"
#define HROMAT_9001_DEVICE_ARHIVE_VIEW_SEKT     "DEVICE_ARHIVE_VIEW_FORM"
#define HROMAT_REG_KEY 	                        SOFTWARE_REG_KEY"\\"HROMAT_9001_SEKT




#endif
